services:
  backend:
    build: ./backend/
    ports:
      - 8080:8080
    command: "uvicorn components.endpoints.endpoints:app --reload --host 0.0.0.0 --port 8080"
    volumes:
      - ./backend:/app
    depends_on:
      - db
  migrations:
    build: ./backend/
    command: bash -c "alembic upgrade head"
    volumes:
      - ./backend:/app
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'expense_tracker'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
